services:
  database:
    image: '{imageName}'
    ports:
      - '1433'
    environment:
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
      - 'ACCEPT_EULA=yes'
    labels:
      org.springframework.boot.jdbc.parameters: sendStringParametersAsUnicode=false